### ISSUE TITLE
Python example has invalid syntax

### ISSUE THREAD

**Issue by ghost** [SAP/quality-continuous-traceability-monitor#13]
Hello,

line 19 needs to be intended to be valid Python syntax.

https://github.com/SAP/quality-continuous-traceability-monitor/blob/a39d913ac93d9769e7083f8dd80e584b52efe851/examples/codeAnnotationExamples/AnnotatedPythonTest.py#L18..L19
Thanks,

Michael

**Comment by ghost** [comment]
In the same vein: the Python example in the wiki should have `#` to start the comment, not `//`:

https://github.com/SAP/quality-continuous-traceability-monitor/wiki/CTM-Guidebook#code-annotations

Thanks!

**Comment by doergn** [comment]
Thanks for reporting @mhaas-work!
Fixed in wiki and with fb8a5204d4f341ceb11144d763851ef13ac6c623
